version: "3.8"

services:
  bot:
    build: .
    container_name: fitness-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - fitness-network

  mongo:
    image: mongo:latest
    container_name: mongo-fitnes
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data/db:/data/db
    networks:
      - fitness-network
networks:
  fitness-network:
